---
title: Synchroonzwemmen
hero_image: images/banner.png
description: Vier de Olympische Spelen door een gesynchroniseerde zwemroutine te programmeren.
duration: 2
listed: true
copyedit: true
version: 4
last_tested: 2019-03-21
steps:
- title: Inleiding
  completion: engaged
- title: Links en rechts zwemmen
- title: Van uiterlijk veranderen
- title: Maak het team
- title: Muziek!
  completion: internal
- title: Geprogrammeerde routines
- title: 'Uitdaging: codeer je eigen routine'
  challenge: true
- title: 'Uitdaging: verander het team'
  challenge: true
- title: Wat kun je verder nog doen?
