---
title: Synchronised swimming
hero_image: images/banner.png
description: Celebrate the Olympics by programming a synchronised swimming routine
original_url: https://codeclubprojects.org/en-GB/scratch/synchronised-swimming
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: scratch
steps:
- title: Introduction
- title: Swimming left and right
- title: Changing costume
- title: Create the team
- title: Music!
- title: Programmed routines
- title: 'Challenge: code your own routine'
- title: 'Challenge: change the team'
site_areas: codeclub, scratch

