---
title: Synchronised Swimming
hero_image: images/synchronised-swimming.png
theme: red
description: Celebrate the Olympics by programming a synchronised swimming routine.
original_url: https://codeclubprojects.org/en-GB/scratch/synchronised-swimming
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Swimming left and right
- title: Changing costume
- title: Create the team
- title: Music!
- title: Programmed routines
- title: 'Challenge: code your own routine'
- title: 'Challenge: change the team'
site_areas: projects