---
title: Synchronised Swimming
description: Celebrate the Olympics by programming a synchronised swimming routine.
original_url: https://codeclubprojects.org/en-GB/scratch/synchronised-swimming
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Swimming Left and Right
- title: Changing costume
- title: Create the team
- title: Music!
- title: Programmed Routines
- title: 'Challenge: Code your own routine'
- title: 'Challenge: Change the team'

