---
title: एडजस्ट तैराकी
hero_image: images/banner.png
description: ओलंपिक का जशन सिंक्रोनाइज़्ड तैराकी  की प्रोग्रामिंग कर के मनाएं I
duration: 2
listed: true
copyedit: true
version: 4
last_tested: 2019-03-21
steps:
  - 
    title: परिचय
  - 
    title: बाएं और दाएं तैरना
  - 
    title: वेशभूषा बदलना
    completion:
      - engaged
  - 
    title: टीम बनाएं
  - 
    title: संगीत!
  - 
    title: प्रोग्राम की गई रूटीन 
    completion:
      - internal
  - 
    title: 'चुनौती: अपनी खुद की रूटीन कोड'
    challenge: true
  - 
    title: 'चुनौती: टीम बदलो'
    challenge: true
  - 
    title: आगे क्या है?
