---
title: Nado sincronizado
hero_image: images/banner.png
description: Celebre as Olimpíadas programando uma rotina de natação sincronizada.
duration: 2
listed: true
copyedit: true
version: 4
last_tested: 2019-03-21
steps:
  - 
    title: Introdução
  - 
    title: Natação esquerda e direita
  - 
    title: Trocando de fantasia
  - 
    title: Criar uma equipe
  - 
    title: Música!
  - 
    title: Rotinas programadas
  - 
    title: 'Desafio: codifique sua própria rotina'
    challenge: true
  - 
    title: 'Desafio: mudar de equipe'
    challenge: true
  - 
    title: 'E agora?'
