---
title: Nado sincronizado
hero_image: images/banner.png
description: Celebra los Juegos Olímpicos programando una rutina de nado sincronizado.
duration: 2
listed: true
copyedit: true
version: 4
last_tested: 2019-03-21
steps:
  - 
    title: Introducción
  - 
    title: Nadar a la izquierda y derecha
  - 
    title: Cambio de vestuario
    completion:
      - engaged
  - 
    title: Crea el equipo
  - 
    title: '¡Música!'
  - 
    title: Rutinas programadas
    completion:
      - internal
  - 
    title: 'Desafío: codifica tu propia rutina'
    challenge: true
  - 
    title: 'Desafío: cambia el equipo'
    challenge: true
  - 
    title: '¿Qué sigue?'
