---
title: Natation synchronisée
hero_image: images/banner.png
description: Célèbre les Jeux olympiques en programmant une chorégraphie de natation
  synchronisée.
duration: 2
listed: true
copyedit: true
version: 4
last_tested: 2019-03-21
steps:
- title: Introduction
- title: Nager à gauche et à droite
- title: Changement de costume
  completion:
  - engaged
- title: Créer l'équipe
- title: Musique!
- title: Chorégraphies programmées
  completion:
  - internal
- title: 'Défi: coder ta propre chorégraphie'
  challenge: true
- title: 'Défi: changer l''équipe'
  challenge: true