---
title: Senkronize yüzme
hero_image: images/banner.png
description: Senkronize bir yüzme rutini programlayarak Olimpiyatları kutlayın.
duration: 2
listed: true
copyedit: true
version: 4
last_tested: 2019-03-21
steps:
- title: Giriş
- title: Sağa ve sola yüzme
- title: Kostüm değiştirme
  completion:
  - engaged
- title: Takım oluştur
- title: Müzik!
- title: Programlanmış rutinler
  completion:
  - internal
- title: 'Meydan Okuma: kendi rutininizi oluşturun'
  challenge: true
- title: 'Meydan Okuma: takımı değiştir'
  challenge: true